/*
Deployment script for AhitofelProject

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "AhitofelProject"
:setvar DefaultFilePrefix "AhitofelProject"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating Table [dbo].[Addresses]...';


GO
CREATE TABLE [dbo].[Addresses] (
    [AddressID]   INT          IDENTITY (1, 1) NOT NULL,
    [Country]     VARCHAR (50) NOT NULL,
    [City]        VARCHAR (50) NOT NULL,
    [Street]      VARCHAR (50) NOT NULL,
    [HouseNumber] INT          NOT NULL,
    [Apartment]   INT          NOT NULL,
    [zipcode]     VARCHAR (10) NULL,
    CONSTRAINT [PK_Addresses] PRIMARY KEY CLUSTERED ([AddressID] ASC),
    CONSTRAINT [Uniqe_Addresses] UNIQUE NONCLUSTERED ([Country] ASC, [City] ASC, [Street] ASC, [HouseNumber] ASC, [Apartment] ASC)
);


GO
PRINT N'Creating Table [dbo].[Cakes]...';


GO
CREATE TABLE [dbo].[Cakes] (
    [CakeID]   INT           IDENTITY (1, 1) NOT NULL,
    [CakeType] VARCHAR (128) NOT NULL,
    CONSTRAINT [PK_Cakes] PRIMARY KEY CLUSTERED ([CakeID] ASC),
    CONSTRAINT [TYPE_Cakes] UNIQUE NONCLUSTERED ([CakeType] ASC)
);


GO
PRINT N'Creating Table [dbo].[ConsultantAddresses]...';


GO
CREATE TABLE [dbo].[ConsultantAddresses] (
    [ConsultantID]   INT NOT NULL,
    [AddressID]      INT NOT NULL,
    [Main/Secondary] BIT NOT NULL,
    CONSTRAINT [PK_ConsultantAdresses] PRIMARY KEY CLUSTERED ([ConsultantID] ASC, [AddressID] ASC),
    CONSTRAINT [mainsecondary_ConsultantAddresses] UNIQUE NONCLUSTERED ([ConsultantID] ASC, [Main/Secondary] ASC)
);


GO
PRINT N'Creating Table [dbo].[ConsultantChildren]...';


GO
CREATE TABLE [dbo].[ConsultantChildren] (
    [ChildID]      INT          IDENTITY (1, 1) NOT NULL,
    [FirstName]    VARCHAR (50) NOT NULL,
    [LastName]     VARCHAR (50) NOT NULL,
    [TZ]           NCHAR (9)    NOT NULL,
    [ConsultantID] INT          NOT NULL,
    [BirthDate]    DATE         NOT NULL,
    [AdressID]     INT          NOT NULL,
    CONSTRAINT [PK_Childrens] PRIMARY KEY CLUSTERED ([ChildID] ASC),
    CONSTRAINT [TZ_ConsultantChildren] UNIQUE NONCLUSTERED ([TZ] ASC)
);


GO
PRINT N'Creating Table [dbo].[Consultants]...';


GO
CREATE TABLE [dbo].[Consultants] (
    [ConsultantID]          INT           IDENTITY (1, 1) NOT NULL,
    [Firstname]             VARCHAR (100) NOT NULL,
    [Lastname]              VARCHAR (100) NOT NULL,
    [ID]                    VARCHAR (9)   NOT NULL,
    [BasicSalary]           MONEY         NOT NULL,
    [GenderID]              INT           NOT NULL,
    [StartDate]             DATETIME      NOT NULL,
    [EndDate]               DATETIME      NULL,
    [MartialStatus]         INT           NOT NULL,
    [PartnerFirstName]      VARCHAR (50)  NULL,
    [PartnerLastName]       VARCHAR (50)  NULL,
    [GenderID_Partner]      INT           NULL,
    [AddressID_Partner]     INT           NULL,
    [Warning]               BIT           NOT NULL,
    [dismissal]             BIT           NOT NULL,
    [TeamID]                INT           NOT NULL,
    [SocialID]              INT           NOT NULL,
    [AnnualVacationCounter] INT           NOT NULL,
    CONSTRAINT [PK_Consultants] PRIMARY KEY CLUSTERED ([ConsultantID] ASC),
    CONSTRAINT [ID_Consultants] UNIQUE NONCLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating Table [dbo].[ConsultingHours]...';


GO
CREATE TABLE [dbo].[ConsultingHours] (
    [ConsulationID]     INT      IDENTITY (1, 1) NOT NULL,
    [ProjectID]         INT      NOT NULL,
    [ConsultantID]      INT      NOT NULL,
    [CustomerAddressID] INT      NOT NULL,
    [StartTime]         DATETIME NOT NULL,
    [EndTime]           DATETIME NOT NULL,
    [Valid]             BIT      NOT NULL,
    [TotalHours]        INT      NOT NULL,
    CONSTRAINT [PK_ConsultingHours] PRIMARY KEY CLUSTERED ([ConsulationID] ASC)
);


GO
PRINT N'Creating Table [dbo].[CurrencyExchange]...';


GO
CREATE TABLE [dbo].[CurrencyExchange] (
    [ExchangeDate] DATE       NOT NULL,
    [ExchangeRate] FLOAT (53) NOT NULL,
    CONSTRAINT [PK_CurrencyExchange] PRIMARY KEY CLUSTERED ([ExchangeDate] ASC)
);


GO
PRINT N'Creating Table [dbo].[CustomerAddresses]...';


GO
CREATE TABLE [dbo].[CustomerAddresses] (
    [CustomerAddressID] INT           IDENTITY (1, 1) NOT NULL,
    [Country]           VARCHAR (100) NOT NULL,
    [City]              VARCHAR (100) NOT NULL,
    [Street]            VARCHAR (100) NOT NULL,
    [HouseNumber]       INT           NOT NULL,
    [OfficeNum]         INT           NOT NULL,
    [Distance]          FLOAT (53)    NOT NULL,
    CONSTRAINT [PK_CustomerAddresses] PRIMARY KEY CLUSTERED ([CustomerAddressID] ASC),
    CONSTRAINT [uniqe_CustomerAddresses] UNIQUE NONCLUSTERED ([Country] ASC, [City] ASC, [Street] ASC, [HouseNumber] ASC, [OfficeNum] ASC)
);


GO
PRINT N'Creating Table [dbo].[Customers]...';


GO
CREATE TABLE [dbo].[Customers] (
    [CustomerID]     INT           IDENTITY (1, 1) NOT NULL,
    [ComanyName]     VARCHAR (MAX) NOT NULL,
    [ForeignCompany] BIT           NOT NULL,
    [BlackCompany]   BIT           NOT NULL,
    CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED ([CustomerID] ASC)
);


GO
PRINT N'Creating Table [dbo].[DaysOff]...';


GO
CREATE TABLE [dbo].[DaysOff] (
    [ConsultantID] INT  NOT NULL,
    [DayOff]       DATE NOT NULL,
    CONSTRAINT [PK_DaysOff] PRIMARY KEY CLUSTERED ([ConsultantID] ASC, [DayOff] ASC)
);


GO
PRINT N'Creating Table [dbo].[Gender]...';


GO
CREATE TABLE [dbo].[Gender] (
    [GenderID]   INT          IDENTITY (1, 1) NOT NULL,
    [GenderName] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_Gender] PRIMARY KEY CLUSTERED ([GenderID] ASC),
    CONSTRAINT [uniqe_Gender] UNIQUE NONCLUSTERED ([GenderName] ASC)
);


GO
PRINT N'Creating Table [dbo].[Hearings]...';


GO
CREATE TABLE [dbo].[Hearings] (
    [HearingID]     INT           IDENTITY (1, 1) NOT NULL,
    [ConsulationID] INT           NOT NULL,
    [Description]   VARCHAR (MAX) NOT NULL,
    [Result]        BIT           NOT NULL,
    [HearingDate]   DATETIME      NOT NULL,
    CONSTRAINT [PK_Hearings] PRIMARY KEY CLUSTERED ([HearingID] ASC),
    CONSTRAINT [Uniqe_Consulation] UNIQUE NONCLUSTERED ([ConsulationID] ASC)
);


GO
PRINT N'Creating Table [dbo].[HistoryBillings]...';


GO
CREATE TABLE [dbo].[HistoryBillings] (
    [Bill_ID]           INT           NOT NULL,
    [ProjectID]         INT           NOT NULL,
    [CustomerID]        INT           NOT NULL,
    [ExchangeDateID]    DATE          NULL,
    [GeneralValues_VAT] FLOAT (53)    NULL,
    [BillDate]          DATE          NOT NULL,
    [LastDayPayment]    DATE          NOT NULL,
    [PaymentDate]       DATE          NULL,
    [TotalBill]         MONEY         NOT NULL,
    [StartTime]         DATETIME2 (7) NOT NULL,
    [EndTime]           DATETIME2 (7) NOT NULL
);


GO
PRINT N'Creating Index [dbo].[HistoryBillings].[ix_HistoryBillings]...';


GO
CREATE CLUSTERED INDEX [ix_HistoryBillings]
    ON [dbo].[HistoryBillings]([EndTime] ASC, [StartTime] ASC) WITH (DATA_COMPRESSION = PAGE);


GO
PRINT N'Creating Table [dbo].[HistoryGeneralValues]...';


GO
CREATE TABLE [dbo].[HistoryGeneralValues] (
    [GeneralID]           INT           NOT NULL,
    [ManagerBonus]        FLOAT (53)    NOT NULL,
    [HolidayRate]         FLOAT (53)    NOT NULL,
    [SaturdayRate]        FLOAT (53)    NOT NULL,
    [SaturdayHolidayRate] FLOAT (53)    NOT NULL,
    [ExtraHourRate]       FLOAT (53)    NOT NULL,
    [MaxAge]              INT           NOT NULL,
    [MaxCakes]            INT           NOT NULL,
    [WarningNum]          INT           NOT NULL,
    [BlackProjectRate]    FLOAT (53)    NOT NULL,
    [VAT]                 FLOAT (53)    NOT NULL,
    [HourPerMonth]        INT           NOT NULL,
    [HourPerDay]          INT           NOT NULL,
    [KilometerRate]       MONEY         NOT NULL,
    [StartTime]           DATETIME2 (7) NOT NULL,
    [EndTime]             DATETIME2 (7) NOT NULL
);


GO
PRINT N'Creating Index [dbo].[HistoryGeneralValues].[ix_HistoryGeneralValues]...';


GO
CREATE CLUSTERED INDEX [ix_HistoryGeneralValues]
    ON [dbo].[HistoryGeneralValues]([EndTime] ASC, [StartTime] ASC) WITH (DATA_COMPRESSION = PAGE);


GO
PRINT N'Creating Table [dbo].[HistoryProjectConsultant]...';


GO
CREATE TABLE [dbo].[HistoryProjectConsultant] (
    [ConsultantID] INT           NOT NULL,
    [ProjectID]    INT           NOT NULL,
    [HourPrice]    FLOAT (53)    NOT NULL,
    [Dollar]       BIT           NOT NULL,
    [StartTime]    DATETIME2 (7) NOT NULL,
    [EndTime]      DATETIME2 (7) NOT NULL
);


GO
PRINT N'Creating Index [dbo].[HistoryProjectConsultant].[ix_HistoryProjectConsultant]...';


GO
CREATE CLUSTERED INDEX [ix_HistoryProjectConsultant]
    ON [dbo].[HistoryProjectConsultant]([EndTime] ASC, [StartTime] ASC) WITH (DATA_COMPRESSION = PAGE);


GO
PRINT N'Creating Table [dbo].[HistorySocialRates]...';


GO
CREATE TABLE [dbo].[HistorySocialRates] (
    [Social_ID]  INT           NOT NULL,
    [SocialRate] FLOAT (53)    NOT NULL,
    [StartTime]  DATETIME2 (7) NOT NULL,
    [EndTime]    DATETIME2 (7) NOT NULL
);


GO
PRINT N'Creating Index [dbo].[HistorySocialRates].[ix_HistorySocialRates]...';


GO
CREATE CLUSTERED INDEX [ix_HistorySocialRates]
    ON [dbo].[HistorySocialRates]([EndTime] ASC, [StartTime] ASC) WITH (DATA_COMPRESSION = PAGE);


GO
PRINT N'Creating Table [dbo].[HistoryTaxPoints]...';


GO
CREATE TABLE [dbo].[HistoryTaxPoints] (
    [TaxPointID]     INT           NOT NULL,
    [GenderID]       INT           NOT NULL,
    [TaxPointsAdult] FLOAT (53)    NOT NULL,
    [TaxPointsChild] FLOAT (53)    NOT NULL,
    [StartTime]      DATETIME2 (7) NOT NULL,
    [EndTime]        DATETIME2 (7) NOT NULL
);


GO
PRINT N'Creating Index [dbo].[HistoryTaxPoints].[ix_HistoryTaxPoints]...';


GO
CREATE CLUSTERED INDEX [ix_HistoryTaxPoints]
    ON [dbo].[HistoryTaxPoints]([EndTime] ASC, [StartTime] ASC) WITH (DATA_COMPRESSION = PAGE);


GO
PRINT N'Creating Table [dbo].[Holidays]...';


GO
CREATE TABLE [dbo].[Holidays] (
    [HolidayID]   INT           IDENTITY (1, 1) NOT NULL,
    [HolidayName] VARCHAR (100) NOT NULL,
    [StartDate]   DATETIME      NOT NULL,
    [EndDate]     DATETIME      NOT NULL,
    CONSTRAINT [PK_Holidays] PRIMARY KEY CLUSTERED ([HolidayID] ASC)
);


GO
PRINT N'Creating Table [dbo].[ProjectConsultant]...';


GO
CREATE TABLE [dbo].[ProjectConsultant] (
    [ConsultantID] INT                                         NOT NULL,
    [ProjectID]    INT                                         NOT NULL,
    [HourPrice]    FLOAT (53)                                  NOT NULL,
    [Dollar]       BIT                                         NOT NULL,
    [StartTime]    DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
    [EndTime]      DATETIME2 (7) GENERATED ALWAYS AS ROW END   NOT NULL,
    CONSTRAINT [PK_ProjectsConsultants] PRIMARY KEY CLUSTERED ([ConsultantID] ASC, [ProjectID] ASC),
    PERIOD FOR SYSTEM_TIME ([StartTime], [EndTime])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[dbo].[HistoryProjectConsultant], DATA_CONSISTENCY_CHECK=ON));


GO
PRINT N'Creating Table [dbo].[ProjectManagers]...';


GO
CREATE TABLE [dbo].[ProjectManagers] (
    [ProjectManagerID] INT           IDENTITY (1, 1) NOT NULL,
    [SeniorManagerID]  INT           NOT NULL,
    [FirstName]        VARCHAR (100) NOT NULL,
    [LastName]         VARCHAR (100) NOT NULL,
    [BirthDate]        DATE          NOT NULL,
    [CakeID]           INT           NOT NULL,
    [AddressID]        INT           NOT NULL,
    CONSTRAINT [PK_ProjectManager] PRIMARY KEY CLUSTERED ([ProjectManagerID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Projects]...';


GO
CREATE TABLE [dbo].[Projects] (
    [ProjectID]        INT          IDENTITY (1, 1) NOT NULL,
    [ProjectName]      VARCHAR (50) NULL,
    [CustomerID]       INT          NOT NULL,
    [ProjectManagerID] INT          NOT NULL,
    [TeamID]           INT          NOT NULL,
    [BlackProject]     BIT          NOT NULL,
    CONSTRAINT [PK_Projects] PRIMARY KEY CLUSTERED ([ProjectID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Salaries]...';


GO
CREATE TABLE [dbo].[Salaries] (
    [SalaryID]                   INT        IDENTITY (1, 1) NOT NULL,
    [ConsultantID]               INT        NOT NULL,
    [Social_ID]                  INT        NOT NULL,
    [GeneralValues_ManagerBonus] FLOAT (53) NULL,
    [TaxPointsID]                INT        NOT NULL,
    [TotalSalary]                MONEY      NOT NULL,
    [IncomeTax]                  MONEY      NOT NULL,
    [CompanyProfit]              MONEY      NOT NULL,
    [PaymentDate]                DATE       NULL,
    CONSTRAINT [PK_Salaries] PRIMARY KEY CLUSTERED ([SalaryID] ASC)
);


GO
PRINT N'Creating Table [dbo].[SeniorManagerRelatives]...';


GO
CREATE TABLE [dbo].[SeniorManagerRelatives] (
    [SeniorRelativeID] INT          IDENTITY (1, 1) NOT NULL,
    [SeniorManagerID]  INT          NOT NULL,
    [FirstName]        VARCHAR (50) NOT NULL,
    [LastName]         VARCHAR (50) NOT NULL,
    [BirthDate]        DATE         NOT NULL,
    [CakeID]           INT          NOT NULL,
    CONSTRAINT [PK_SeniorManagerRelatives] PRIMARY KEY CLUSTERED ([SeniorRelativeID] ASC)
);


GO
PRINT N'Creating Table [dbo].[SeniorManagers]...';


GO
CREATE TABLE [dbo].[SeniorManagers] (
    [SeniorManagerID] INT          IDENTITY (1, 1) NOT NULL,
    [Firstname]       VARCHAR (50) NOT NULL,
    [Lastname]        VARCHAR (50) NOT NULL,
    [BirthDate]       DATE         NOT NULL,
    [AddressID]       INT          NOT NULL,
    [CakeID]          INT          NOT NULL,
    CONSTRAINT [PK_SeniorManagers] PRIMARY KEY CLUSTERED ([SeniorManagerID] ASC)
);


GO
PRINT N'Creating Table [dbo].[SocialRates]...';


GO
CREATE TABLE [dbo].[SocialRates] (
    [Social_ID]  INT                                         IDENTITY (1, 1) NOT NULL,
    [SocialRate] FLOAT (53)                                  NOT NULL,
    [StartTime]  DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
    [EndTime]    DATETIME2 (7) GENERATED ALWAYS AS ROW END   NOT NULL,
    CONSTRAINT [PK_SocialRates] PRIMARY KEY CLUSTERED ([Social_ID] ASC),
    CONSTRAINT [IX_SocialRates] UNIQUE NONCLUSTERED ([SocialRate] ASC),
    PERIOD FOR SYSTEM_TIME ([StartTime], [EndTime])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[dbo].[HistorySocialRates], DATA_CONSISTENCY_CHECK=ON));


GO
PRINT N'Creating Table [dbo].[Status]...';


GO
CREATE TABLE [dbo].[Status] (
    [StatusID]      INT          IDENTITY (1, 1) NOT NULL,
    [MartialStatus] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_Status] PRIMARY KEY CLUSTERED ([StatusID] ASC),
    CONSTRAINT [uniqe_status] UNIQUE NONCLUSTERED ([MartialStatus] ASC)
);


GO
PRINT N'Creating Table [dbo].[TaxPoints]...';


GO
CREATE TABLE [dbo].[TaxPoints] (
    [TaxPointID]     INT                                         IDENTITY (1, 1) NOT NULL,
    [GenderID]       INT                                         NOT NULL,
    [TaxPointsAdult] FLOAT (53)                                  NOT NULL,
    [TaxPointsChild] FLOAT (53)                                  NOT NULL,
    [StartTime]      DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
    [EndTime]        DATETIME2 (7) GENERATED ALWAYS AS ROW END   NOT NULL,
    CONSTRAINT [PK_TaxPoints] PRIMARY KEY CLUSTERED ([TaxPointID] ASC),
    CONSTRAINT [gender_TaxPoints] UNIQUE NONCLUSTERED ([GenderID] ASC),
    PERIOD FOR SYSTEM_TIME ([StartTime], [EndTime])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[dbo].[HistoryTaxPoints], DATA_CONSISTENCY_CHECK=ON));


GO
PRINT N'Creating Table [dbo].[Teams]...';


GO
CREATE TABLE [dbo].[Teams] (
    [TeamID]     INT IDENTITY (1, 1) NOT NULL,
    [TeamLeader] INT NOT NULL,
    CONSTRAINT [PK_TeamLead] PRIMARY KEY CLUSTERED ([TeamID] ASC),
    CONSTRAINT [uniqe_leader] UNIQUE NONCLUSTERED ([TeamLeader] ASC)
);


GO
PRINT N'Creating Table [dbo].[Billings]...';


GO
CREATE TABLE [dbo].[Billings] (
    [Bill_ID]           INT                                         IDENTITY (1, 1) NOT NULL,
    [ProjectID]         INT                                         NOT NULL,
    [CustomerID]        INT                                         NOT NULL,
    [ExchangeDateID]    DATE                                        NULL,
    [GeneralValues_VAT] FLOAT (53)                                  NULL,
    [BillDate]          DATE                                        NOT NULL,
    [LastDayPayment]    DATE                                        NOT NULL,
    [PaymentDate]       DATE                                        NULL,
    [TotalBill]         MONEY                                       NOT NULL,
    [StartTime]         DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
    [EndTime]           DATETIME2 (7) GENERATED ALWAYS AS ROW END   NOT NULL,
    CONSTRAINT [PK_Bills] PRIMARY KEY CLUSTERED ([Bill_ID] ASC),
    PERIOD FOR SYSTEM_TIME ([StartTime], [EndTime])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[dbo].[HistoryBillings], DATA_CONSISTENCY_CHECK=ON));


GO
PRINT N'Creating Table [dbo].[GeneralValues]...';


GO
CREATE TABLE [dbo].[GeneralValues] (
    [GeneralID]           INT                                         NOT NULL,
    [ManagerBonus]        FLOAT (53)                                  NOT NULL,
    [HolidayRate]         FLOAT (53)                                  NOT NULL,
    [SaturdayRate]        FLOAT (53)                                  NOT NULL,
    [SaturdayHolidayRate] FLOAT (53)                                  NOT NULL,
    [ExtraHourRate]       FLOAT (53)                                  NOT NULL,
    [MaxAge]              INT                                         NOT NULL,
    [MaxCakes]            INT                                         NOT NULL,
    [WarningNum]          INT                                         NOT NULL,
    [BlackProjectRate]    FLOAT (53)                                  NOT NULL,
    [VAT]                 FLOAT (53)                                  NOT NULL,
    [HourPerMonth]        INT                                         NOT NULL,
    [HourPerDay]          INT                                         NOT NULL,
    [KilometerRate]       MONEY                                       NOT NULL,
    [StartTime]           DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
    [EndTime]             DATETIME2 (7) GENERATED ALWAYS AS ROW END   NOT NULL,
    CONSTRAINT [PK_GeneralValues] PRIMARY KEY CLUSTERED ([GeneralID] ASC),
    PERIOD FOR SYSTEM_TIME ([StartTime], [EndTime])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[dbo].[HistoryGeneralValues], DATA_CONSISTENCY_CHECK=ON));


GO
PRINT N'Creating Default Constraint [dbo].[DF_Addresses_Apartment]...';


GO
ALTER TABLE [dbo].[Addresses]
    ADD CONSTRAINT [DF_Addresses_Apartment] DEFAULT ((0)) FOR [Apartment];


GO
PRINT N'Creating Default Constraint [dbo].[DF_employees_Worning]...';


GO
ALTER TABLE [dbo].[Consultants]
    ADD CONSTRAINT [DF_employees_Worning] DEFAULT ((0)) FOR [Warning];


GO
PRINT N'Creating Default Constraint [dbo].[DF_employees_Fired]...';


GO
ALTER TABLE [dbo].[Consultants]
    ADD CONSTRAINT [DF_employees_Fired] DEFAULT ((0)) FOR [dismissal];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Consultants_AnnualVacationCounter]...';


GO
ALTER TABLE [dbo].[Consultants]
    ADD CONSTRAINT [DF_Consultants_AnnualVacationCounter] DEFAULT ((0)) FOR [AnnualVacationCounter];


GO
PRINT N'Creating Default Constraint [dbo].[DF_ConsultingHours_Valid]...';


GO
ALTER TABLE [dbo].[ConsultingHours]
    ADD CONSTRAINT [DF_ConsultingHours_Valid] DEFAULT ((1)) FOR [Valid];


GO
PRINT N'Creating Default Constraint [dbo].[DF_CustomerAddresses_OfficeNum]...';


GO
ALTER TABLE [dbo].[CustomerAddresses]
    ADD CONSTRAINT [DF_CustomerAddresses_OfficeNum] DEFAULT ((0)) FOR [OfficeNum];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Customers_ForeignCompany]...';


GO
ALTER TABLE [dbo].[Customers]
    ADD CONSTRAINT [DF_Customers_ForeignCompany] DEFAULT ((0)) FOR [ForeignCompany];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Customers_BlackCompany]...';


GO
ALTER TABLE [dbo].[Customers]
    ADD CONSTRAINT [DF_Customers_BlackCompany] DEFAULT ((0)) FOR [BlackCompany];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Hearings_Result]...';


GO
ALTER TABLE [dbo].[Hearings]
    ADD CONSTRAINT [DF_Hearings_Result] DEFAULT ((0)) FOR [Result];


GO
PRINT N'Creating Default Constraint [dbo].[DF_ProjectsConsultants_Dollar]...';


GO
ALTER TABLE [dbo].[ProjectConsultant]
    ADD CONSTRAINT [DF_ProjectsConsultants_Dollar] DEFAULT ((0)) FOR [Dollar];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Projects_BlackProject]...';


GO
ALTER TABLE [dbo].[Projects]
    ADD CONSTRAINT [DF_Projects_BlackProject] DEFAULT ((0)) FOR [BlackProject];


GO
PRINT N'Creating Foreign Key [dbo].[FK_Bills_CurrencyExchange]...';


GO
ALTER TABLE [dbo].[Billings] WITH NOCHECK
    ADD CONSTRAINT [FK_Bills_CurrencyExchange] FOREIGN KEY ([ExchangeDateID]) REFERENCES [dbo].[CurrencyExchange] ([ExchangeDate]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Bills_Customers]...';


GO
ALTER TABLE [dbo].[Billings] WITH NOCHECK
    ADD CONSTRAINT [FK_Bills_Customers] FOREIGN KEY ([CustomerID]) REFERENCES [dbo].[Customers] ([CustomerID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Bills_Projects]...';


GO
ALTER TABLE [dbo].[Billings] WITH NOCHECK
    ADD CONSTRAINT [FK_Bills_Projects] FOREIGN KEY ([ProjectID]) REFERENCES [dbo].[Projects] ([ProjectID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ConsultantAddresses_Addresses]...';


GO
ALTER TABLE [dbo].[ConsultantAddresses] WITH NOCHECK
    ADD CONSTRAINT [FK_ConsultantAddresses_Addresses] FOREIGN KEY ([AddressID]) REFERENCES [dbo].[Addresses] ([AddressID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ConsultantAddresses_Consultants]...';


GO
ALTER TABLE [dbo].[ConsultantAddresses] WITH NOCHECK
    ADD CONSTRAINT [FK_ConsultantAddresses_Consultants] FOREIGN KEY ([ConsultantID]) REFERENCES [dbo].[Consultants] ([ConsultantID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ConsultantChildren_Addresses]...';


GO
ALTER TABLE [dbo].[ConsultantChildren] WITH NOCHECK
    ADD CONSTRAINT [FK_ConsultantChildren_Addresses] FOREIGN KEY ([AdressID]) REFERENCES [dbo].[Addresses] ([AddressID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ConsultantChildren_Consultants]...';


GO
ALTER TABLE [dbo].[ConsultantChildren] WITH NOCHECK
    ADD CONSTRAINT [FK_ConsultantChildren_Consultants] FOREIGN KEY ([ConsultantID]) REFERENCES [dbo].[Consultants] ([ConsultantID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Consultants_Addresses]...';


GO
ALTER TABLE [dbo].[Consultants] WITH NOCHECK
    ADD CONSTRAINT [FK_Consultants_Addresses] FOREIGN KEY ([AddressID_Partner]) REFERENCES [dbo].[Addresses] ([AddressID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Consultants_Gender]...';


GO
ALTER TABLE [dbo].[Consultants] WITH NOCHECK
    ADD CONSTRAINT [FK_Consultants_Gender] FOREIGN KEY ([GenderID]) REFERENCES [dbo].[Gender] ([GenderID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Consultants_Gender1]...';


GO
ALTER TABLE [dbo].[Consultants] WITH NOCHECK
    ADD CONSTRAINT [FK_Consultants_Gender1] FOREIGN KEY ([GenderID_Partner]) REFERENCES [dbo].[Gender] ([GenderID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Consultants_SocialRates]...';


GO
ALTER TABLE [dbo].[Consultants] WITH NOCHECK
    ADD CONSTRAINT [FK_Consultants_SocialRates] FOREIGN KEY ([SocialID]) REFERENCES [dbo].[SocialRates] ([Social_ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Consultants_Status]...';


GO
ALTER TABLE [dbo].[Consultants] WITH NOCHECK
    ADD CONSTRAINT [FK_Consultants_Status] FOREIGN KEY ([MartialStatus]) REFERENCES [dbo].[Status] ([StatusID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ConsultingHours_Consultants]...';


GO
ALTER TABLE [dbo].[ConsultingHours] WITH NOCHECK
    ADD CONSTRAINT [FK_ConsultingHours_Consultants] FOREIGN KEY ([ConsultantID]) REFERENCES [dbo].[Consultants] ([ConsultantID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ConsultingHours_CustomerAddresses]...';


GO
ALTER TABLE [dbo].[ConsultingHours] WITH NOCHECK
    ADD CONSTRAINT [FK_ConsultingHours_CustomerAddresses] FOREIGN KEY ([CustomerAddressID]) REFERENCES [dbo].[CustomerAddresses] ([CustomerAddressID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ConsultingHours_Projects]...';


GO
ALTER TABLE [dbo].[ConsultingHours] WITH NOCHECK
    ADD CONSTRAINT [FK_ConsultingHours_Projects] FOREIGN KEY ([ProjectID]) REFERENCES [dbo].[Projects] ([ProjectID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_DaysOff_Consultants]...';


GO
ALTER TABLE [dbo].[DaysOff] WITH NOCHECK
    ADD CONSTRAINT [FK_DaysOff_Consultants] FOREIGN KEY ([ConsultantID]) REFERENCES [dbo].[Consultants] ([ConsultantID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Hearings_ConsultingHours]...';


GO
ALTER TABLE [dbo].[Hearings] WITH NOCHECK
    ADD CONSTRAINT [FK_Hearings_ConsultingHours] FOREIGN KEY ([ConsulationID]) REFERENCES [dbo].[ConsultingHours] ([ConsulationID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProjectConsultant_Consultants]...';


GO
ALTER TABLE [dbo].[ProjectConsultant] WITH NOCHECK
    ADD CONSTRAINT [FK_ProjectConsultant_Consultants] FOREIGN KEY ([ConsultantID]) REFERENCES [dbo].[Consultants] ([ConsultantID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProjectConsultant_Projects]...';


GO
ALTER TABLE [dbo].[ProjectConsultant] WITH NOCHECK
    ADD CONSTRAINT [FK_ProjectConsultant_Projects] FOREIGN KEY ([ProjectID]) REFERENCES [dbo].[Projects] ([ProjectID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProjectManager_Addresses]...';


GO
ALTER TABLE [dbo].[ProjectManagers] WITH NOCHECK
    ADD CONSTRAINT [FK_ProjectManager_Addresses] FOREIGN KEY ([AddressID]) REFERENCES [dbo].[Addresses] ([AddressID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProjectManager_Cakes]...';


GO
ALTER TABLE [dbo].[ProjectManagers] WITH NOCHECK
    ADD CONSTRAINT [FK_ProjectManager_Cakes] FOREIGN KEY ([CakeID]) REFERENCES [dbo].[Cakes] ([CakeID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProjectManager_SeniorManagers]...';


GO
ALTER TABLE [dbo].[ProjectManagers] WITH NOCHECK
    ADD CONSTRAINT [FK_ProjectManager_SeniorManagers] FOREIGN KEY ([SeniorManagerID]) REFERENCES [dbo].[SeniorManagers] ([SeniorManagerID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Projects_Customers]...';


GO
ALTER TABLE [dbo].[Projects] WITH NOCHECK
    ADD CONSTRAINT [FK_Projects_Customers] FOREIGN KEY ([CustomerID]) REFERENCES [dbo].[Customers] ([CustomerID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Projects_ProjectManager]...';


GO
ALTER TABLE [dbo].[Projects] WITH NOCHECK
    ADD CONSTRAINT [FK_Projects_ProjectManager] FOREIGN KEY ([ProjectManagerID]) REFERENCES [dbo].[ProjectManagers] ([ProjectManagerID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Projects_Teams]...';


GO
ALTER TABLE [dbo].[Projects] WITH NOCHECK
    ADD CONSTRAINT [FK_Projects_Teams] FOREIGN KEY ([TeamID]) REFERENCES [dbo].[Teams] ([TeamID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Salaries_Consultants]...';


GO
ALTER TABLE [dbo].[Salaries] WITH NOCHECK
    ADD CONSTRAINT [FK_Salaries_Consultants] FOREIGN KEY ([ConsultantID]) REFERENCES [dbo].[Consultants] ([ConsultantID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Salaries_SocialRates]...';


GO
ALTER TABLE [dbo].[Salaries] WITH NOCHECK
    ADD CONSTRAINT [FK_Salaries_SocialRates] FOREIGN KEY ([Social_ID]) REFERENCES [dbo].[SocialRates] ([Social_ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Salaries_TaxPoints]...';


GO
ALTER TABLE [dbo].[Salaries] WITH NOCHECK
    ADD CONSTRAINT [FK_Salaries_TaxPoints] FOREIGN KEY ([TaxPointsID]) REFERENCES [dbo].[TaxPoints] ([TaxPointID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_SeniorManagerRelatives_Cakes]...';


GO
ALTER TABLE [dbo].[SeniorManagerRelatives] WITH NOCHECK
    ADD CONSTRAINT [FK_SeniorManagerRelatives_Cakes] FOREIGN KEY ([CakeID]) REFERENCES [dbo].[Cakes] ([CakeID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_SeniorManagerRelatives_SeniorManagers]...';


GO
ALTER TABLE [dbo].[SeniorManagerRelatives] WITH NOCHECK
    ADD CONSTRAINT [FK_SeniorManagerRelatives_SeniorManagers] FOREIGN KEY ([SeniorManagerID]) REFERENCES [dbo].[SeniorManagers] ([SeniorManagerID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_SeniorManagers_Addresses]...';


GO
ALTER TABLE [dbo].[SeniorManagers] WITH NOCHECK
    ADD CONSTRAINT [FK_SeniorManagers_Addresses] FOREIGN KEY ([AddressID]) REFERENCES [dbo].[Addresses] ([AddressID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_SeniorManagers_Cakes]...';


GO
ALTER TABLE [dbo].[SeniorManagers] WITH NOCHECK
    ADD CONSTRAINT [FK_SeniorManagers_Cakes] FOREIGN KEY ([CakeID]) REFERENCES [dbo].[Cakes] ([CakeID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_TaxPoints_Gender]...';


GO
ALTER TABLE [dbo].[TaxPoints] WITH NOCHECK
    ADD CONSTRAINT [FK_TaxPoints_Gender] FOREIGN KEY ([GenderID]) REFERENCES [dbo].[Gender] ([GenderID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Teams_Consultants]...';


GO
ALTER TABLE [dbo].[Teams] WITH NOCHECK
    ADD CONSTRAINT [FK_Teams_Consultants] FOREIGN KEY ([TeamLeader]) REFERENCES [dbo].[Consultants] ([ConsultantID]);


GO
PRINT N'Creating Extended Property [dbo].[Billings].[GeneralValues_VAT].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'ערך מפונקציה', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Billings', @level2type = N'COLUMN', @level2name = N'GeneralValues_VAT';


GO
PRINT N'Creating Extended Property [dbo].[Billings].[LastDayPayment].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'יחושב 30 יום קדימה', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Billings', @level2type = N'COLUMN', @level2name = N'LastDayPayment';


GO
PRINT N'Creating Extended Property [dbo].[Billings].[TotalBill].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'יחושב בפונקציה', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Billings', @level2type = N'COLUMN', @level2name = N'TotalBill';


GO
PRINT N'Creating Extended Property [dbo].[ConsultantAddresses].[Main/Secondary].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'לעובד יש כתובת ראשית ומשנית 0 ראשית', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ConsultantAddresses', @level2type = N'COLUMN', @level2name = N'Main/Secondary';


GO
PRINT N'Creating Extended Property [dbo].[Consultants].[GenderID].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'זכר/נקבה', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Consultants', @level2type = N'COLUMN', @level2name = N'GenderID';


GO
PRINT N'Creating Extended Property [dbo].[Consultants].[Warning].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'אזהרה לאחר שימוע 0/1 ברירת מחדל 0', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Consultants', @level2type = N'COLUMN', @level2name = N'Warning';


GO
PRINT N'Creating Extended Property [dbo].[Consultants].[dismissal].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'0/1 יוכנס לאחר פיטורין', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Consultants', @level2type = N'COLUMN', @level2name = N'dismissal';


GO
PRINT N'Creating Extended Property [dbo].[Consultants].[AnnualVacationCounter].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'תהיה פה צבירת ימים', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Consultants', @level2type = N'COLUMN', @level2name = N'AnnualVacationCounter';


GO
PRINT N'Creating Extended Property [dbo].[ConsultingHours].[Valid].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'דיווח תקין/לא תקין 1 ברירת מחדל , יוכנס ע"י פונקציה', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ConsultingHours', @level2type = N'COLUMN', @level2name = N'Valid';


GO
PRINT N'Creating Extended Property [dbo].[ConsultingHours].[TotalHours].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'שדה מחושב', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ConsultingHours', @level2type = N'COLUMN', @level2name = N'TotalHours';


GO
PRINT N'Creating Extended Property [dbo].[CurrencyExchange].[ExchangeDate].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'נקודת הנחה שיש שער אחד ליום אחד ולכן הדאטה טייפ הוא date', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CurrencyExchange', @level2type = N'COLUMN', @level2name = N'ExchangeDate';


GO
PRINT N'Creating Extended Property [dbo].[Customers].[ForeignCompany].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'לצורך מידע כגון מיסים עקיפים', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Customers', @level2type = N'COLUMN', @level2name = N'ForeignCompany';


GO
PRINT N'Creating Extended Property [dbo].[Customers].[BlackCompany].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'האם הלקוח ברשימה שחורה - יעודכן ע"י פונקציה לפי תשלום', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Customers', @level2type = N'COLUMN', @level2name = N'BlackCompany';


GO
PRINT N'Creating Extended Property [dbo].[DaysOff].[DayOff].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'השמה', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'DaysOff', @level2type = N'COLUMN', @level2name = N'DayOff';


GO
PRINT N'Creating Extended Property [dbo].[Gender].[GenderID].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'זכר/נקבה', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Gender', @level2type = N'COLUMN', @level2name = N'GenderID';


GO
PRINT N'Creating Extended Property [dbo].[Hearings].[Result].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'אשם או לא - 0 זכאי ברירת מחדל', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Hearings', @level2type = N'COLUMN', @level2name = N'Result';


GO
PRINT N'Creating Extended Property [dbo].[Holidays].[StartDate].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'בחגים יכול להיות חפיפה לפי מגזר ולכן אין יחודיות. אם זה טעות אוראל אמר', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Holidays', @level2type = N'COLUMN', @level2name = N'StartDate';


GO
PRINT N'Creating Extended Property [dbo].[Projects].[BlackProject].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'האם הפרוייקט ברשימה השחורה', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Projects', @level2type = N'COLUMN', @level2name = N'BlackProject';


GO
PRINT N'Creating Extended Property [dbo].[Salaries].[GeneralValues_ManagerBonus].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'חישוב פונקציה', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Salaries', @level2type = N'COLUMN', @level2name = N'GeneralValues_ManagerBonus';


GO
PRINT N'Creating Extended Property [dbo].[Salaries].[CompanyProfit].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'פונקציה לחישוב רווח - הכנסה פייר עובד פחות משכורת', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Salaries', @level2type = N'COLUMN', @level2name = N'CompanyProfit';


GO
PRINT N'Creating Extended Property [dbo].[Teams].[TeamLeader].[MS_Description]...';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'ראש צוות', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Teams', @level2type = N'COLUMN', @level2name = N'TeamLeader';


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[Billings] WITH CHECK CHECK CONSTRAINT [FK_Bills_CurrencyExchange];

ALTER TABLE [dbo].[Billings] WITH CHECK CHECK CONSTRAINT [FK_Bills_Customers];

ALTER TABLE [dbo].[Billings] WITH CHECK CHECK CONSTRAINT [FK_Bills_Projects];

ALTER TABLE [dbo].[ConsultantAddresses] WITH CHECK CHECK CONSTRAINT [FK_ConsultantAddresses_Addresses];

ALTER TABLE [dbo].[ConsultantAddresses] WITH CHECK CHECK CONSTRAINT [FK_ConsultantAddresses_Consultants];

ALTER TABLE [dbo].[ConsultantChildren] WITH CHECK CHECK CONSTRAINT [FK_ConsultantChildren_Addresses];

ALTER TABLE [dbo].[ConsultantChildren] WITH CHECK CHECK CONSTRAINT [FK_ConsultantChildren_Consultants];

ALTER TABLE [dbo].[Consultants] WITH CHECK CHECK CONSTRAINT [FK_Consultants_Addresses];

ALTER TABLE [dbo].[Consultants] WITH CHECK CHECK CONSTRAINT [FK_Consultants_Gender];

ALTER TABLE [dbo].[Consultants] WITH CHECK CHECK CONSTRAINT [FK_Consultants_Gender1];

ALTER TABLE [dbo].[Consultants] WITH CHECK CHECK CONSTRAINT [FK_Consultants_SocialRates];

ALTER TABLE [dbo].[Consultants] WITH CHECK CHECK CONSTRAINT [FK_Consultants_Status];

ALTER TABLE [dbo].[ConsultingHours] WITH CHECK CHECK CONSTRAINT [FK_ConsultingHours_Consultants];

ALTER TABLE [dbo].[ConsultingHours] WITH CHECK CHECK CONSTRAINT [FK_ConsultingHours_CustomerAddresses];

ALTER TABLE [dbo].[ConsultingHours] WITH CHECK CHECK CONSTRAINT [FK_ConsultingHours_Projects];

ALTER TABLE [dbo].[DaysOff] WITH CHECK CHECK CONSTRAINT [FK_DaysOff_Consultants];

ALTER TABLE [dbo].[Hearings] WITH CHECK CHECK CONSTRAINT [FK_Hearings_ConsultingHours];

ALTER TABLE [dbo].[ProjectConsultant] WITH CHECK CHECK CONSTRAINT [FK_ProjectConsultant_Consultants];

ALTER TABLE [dbo].[ProjectConsultant] WITH CHECK CHECK CONSTRAINT [FK_ProjectConsultant_Projects];

ALTER TABLE [dbo].[ProjectManagers] WITH CHECK CHECK CONSTRAINT [FK_ProjectManager_Addresses];

ALTER TABLE [dbo].[ProjectManagers] WITH CHECK CHECK CONSTRAINT [FK_ProjectManager_Cakes];

ALTER TABLE [dbo].[ProjectManagers] WITH CHECK CHECK CONSTRAINT [FK_ProjectManager_SeniorManagers];

ALTER TABLE [dbo].[Projects] WITH CHECK CHECK CONSTRAINT [FK_Projects_Customers];

ALTER TABLE [dbo].[Projects] WITH CHECK CHECK CONSTRAINT [FK_Projects_ProjectManager];

ALTER TABLE [dbo].[Projects] WITH CHECK CHECK CONSTRAINT [FK_Projects_Teams];

ALTER TABLE [dbo].[Salaries] WITH CHECK CHECK CONSTRAINT [FK_Salaries_Consultants];

ALTER TABLE [dbo].[Salaries] WITH CHECK CHECK CONSTRAINT [FK_Salaries_SocialRates];

ALTER TABLE [dbo].[Salaries] WITH CHECK CHECK CONSTRAINT [FK_Salaries_TaxPoints];

ALTER TABLE [dbo].[SeniorManagerRelatives] WITH CHECK CHECK CONSTRAINT [FK_SeniorManagerRelatives_Cakes];

ALTER TABLE [dbo].[SeniorManagerRelatives] WITH CHECK CHECK CONSTRAINT [FK_SeniorManagerRelatives_SeniorManagers];

ALTER TABLE [dbo].[SeniorManagers] WITH CHECK CHECK CONSTRAINT [FK_SeniorManagers_Addresses];

ALTER TABLE [dbo].[SeniorManagers] WITH CHECK CHECK CONSTRAINT [FK_SeniorManagers_Cakes];

ALTER TABLE [dbo].[TaxPoints] WITH CHECK CHECK CONSTRAINT [FK_TaxPoints_Gender];

ALTER TABLE [dbo].[Teams] WITH CHECK CHECK CONSTRAINT [FK_Teams_Consultants];


GO
PRINT N'Update complete.';


GO
